import type { NoteDoc, PYQPaper, SkillPost } from "@/stores";

export type Difficulty = "easy" | "medium" | "hard";
export type QuizQuestion = { id: string; subject: string; topic: string; skill: string; difficulty: Difficulty; prompt: string; options: string[]; answer: number; explanation: string };
export type LearningEvent = { id: string; userId: string; type: "question" | "resource" | "quiz" | "goal"; itemId: string; subject?: string; topic?: string; correct?: boolean; score?: number; durationSec?: number; createdAt: string };
export type LearningProfile = { id: string; userId: string; subjects: string[]; topics: string[]; availability: string; goal: string; updatedAt: string };
export type ResourceRecommendation = { id: string; kind: "note" | "pyq" | "skill"; title: string; subtitle: string; url: string; score: number; reason: string };

export const QUESTION_BANK: QuizQuestion[] = [
  { id: "math-vectors-1", subject: "Mathematics", topic: "Vectors", skill: "dot product", difficulty: "easy", prompt: "If a·b = 0 for two non-zero vectors, what is their relationship?", options: ["Parallel", "Perpendicular", "Equal", "Opposite"], answer: 1, explanation: "A zero dot product means the vectors are perpendicular." },
  { id: "math-vectors-2", subject: "Mathematics", topic: "Vectors", skill: "magnitude", difficulty: "medium", prompt: "What is the magnitude of 3i + 4j?", options: ["5", "7", "12", "25"], answer: 0, explanation: "Magnitude = √(3² + 4²) = 5." },
  { id: "math-vectors-3", subject: "Mathematics", topic: "Vectors", skill: "cross product", difficulty: "hard", prompt: "The magnitude of a×b equals zero when the vectors are:", options: ["Perpendicular", "Parallel or antiparallel", "Unit vectors", "Equal in magnitude only"], answer: 1, explanation: "|a×b| = |a||b|sinθ, so it vanishes when θ is 0° or 180°." },
  { id: "math-sequences-1", subject: "Mathematics", topic: "Sequences", skill: "arithmetic progression", difficulty: "easy", prompt: "The common difference of 5, 9, 13, 17 is:", options: ["2", "3", "4", "5"], answer: 2, explanation: "Each term increases by 4." },
  { id: "math-sequences-2", subject: "Mathematics", topic: "Sequences", skill: "AP sum", difficulty: "medium", prompt: "The sum of the first 10 positive integers is:", options: ["45", "50", "55", "60"], answer: 2, explanation: "n(n+1)/2 = 10×11/2 = 55." },
  { id: "math-functions-1", subject: "Mathematics", topic: "Functions", skill: "domain", difficulty: "medium", prompt: "For f(x)=1/(x−2), which value is excluded from the domain?", options: ["−2", "0", "1", "2"], answer: 3, explanation: "The denominator cannot be zero, so x=2 is excluded." },
  { id: "physics-vectors-1", subject: "Physics", topic: "Vectors", skill: "components", difficulty: "easy", prompt: "A vector of magnitude 10 at 60° to the x-axis has x-component:", options: ["5", "5√3", "10", "20"], answer: 0, explanation: "x = 10 cos60° = 5." },
  { id: "physics-motion-1", subject: "Physics", topic: "Kinematics", skill: "equations of motion", difficulty: "easy", prompt: "For constant acceleration, which equation relates final velocity, initial velocity, acceleration and displacement?", options: ["v=u+at", "s=ut+½at²", "v²=u²+2as", "s=vt"], answer: 2, explanation: "The third equation is v²=u²+2as." },
  { id: "physics-motion-2", subject: "Physics", topic: "Kinematics", skill: "graphs", difficulty: "medium", prompt: "The area under a velocity–time graph represents:", options: ["Acceleration", "Displacement", "Jerk", "Momentum"], answer: 1, explanation: "Integrating velocity over time gives displacement." },
  { id: "physics-laws-1", subject: "Physics", topic: "Newton's Laws", skill: "second law", difficulty: "medium", prompt: "If net force on an object doubles while mass stays constant, its acceleration:", options: ["Halves", "Doubles", "Stays constant", "Becomes zero"], answer: 1, explanation: "Newton's second law gives a=F/m." },
  { id: "physics-energy-1", subject: "Physics", topic: "Work Energy", skill: "work", difficulty: "hard", prompt: "If a force is perpendicular to displacement, the work done by that force is:", options: ["Maximum", "Negative", "Zero", "Equal to force"], answer: 2, explanation: "W=Fs cosθ and cos90°=0." },
  { id: "chem-mole-1", subject: "Chemistry", topic: "Mole Concept", skill: "moles", difficulty: "easy", prompt: "How many moles are present in 18 g of water?", options: ["0.5", "1", "2", "18"], answer: 1, explanation: "Molar mass of water is 18 g/mol, so 18 g is 1 mol." },
  { id: "chem-mole-2", subject: "Chemistry", topic: "Mole Concept", skill: "particles", difficulty: "medium", prompt: "One mole of any substance contains approximately:", options: ["6.022×10²³ entities", "3.011×10²³ entities", "9.8×10² entities", "1.602×10⁻¹⁹ entities"], answer: 0, explanation: "Avogadro's constant is approximately 6.022×10²³ mol⁻¹." },
  { id: "chem-atomic-1", subject: "Chemistry", topic: "Atomic Structure", skill: "quantum numbers", difficulty: "medium", prompt: "Which quantum number determines the shape of an orbital?", options: ["n", "l", "m", "s"], answer: 1, explanation: "The azimuthal quantum number l determines orbital subshell shape." },
  { id: "chem-periodic-1", subject: "Chemistry", topic: "Periodic Trends", skill: "atomic radius", difficulty: "hard", prompt: "Across a period from left to right, atomic radius generally:", options: ["Increases", "Decreases", "Stays identical", "First becomes infinite"], answer: 1, explanation: "Effective nuclear charge generally increases across a period, pulling electrons closer." },
  { id: "chem-bonding-1", subject: "Chemistry", topic: "Chemical Bonding", skill: "octet", difficulty: "easy", prompt: "The octet rule broadly describes a tendency toward:", options: ["8 valence electrons", "8 neutrons", "8 shells", "8 protons"], answer: 0, explanation: "Many main-group atoms tend toward a stable valence shell configuration resembling eight electrons." },
  { id: "econ-demand-1", subject: "Economics", topic: "Demand", skill: "demand curve", difficulty: "easy", prompt: "Holding other factors constant, a rise in a good's own price generally causes quantity demanded to:", options: ["Rise", "Fall", "Stay fixed", "Become zero always"], answer: 1, explanation: "The law of demand describes an inverse relationship between price and quantity demanded, ceteris paribus." },
  { id: "econ-demand-2", subject: "Economics", topic: "Demand", skill: "elasticity", difficulty: "medium", prompt: "Price elasticity of demand measures responsiveness of quantity demanded to a change in:", options: ["Income", "Price", "Population", "Technology"], answer: 1, explanation: "Price elasticity compares percentage change in quantity demanded with percentage change in price." },
  { id: "econ-supply-1", subject: "Economics", topic: "Supply", skill: "supply curve", difficulty: "easy", prompt: "A typical upward-sloping supply curve means producers are willing to supply more when:", options: ["Price rises", "Price falls", "Taxes disappear", "Demand falls"], answer: 0, explanation: "Ceteris paribus, a higher price can provide greater incentive to supply." },
  { id: "econ-markets-1", subject: "Economics", topic: "Market Equilibrium", skill: "equilibrium", difficulty: "hard", prompt: "Market equilibrium occurs where:", options: ["Demand is zero", "Supply is zero", "Quantity demanded equals quantity supplied", "Price is always zero"], answer: 2, explanation: "Equilibrium is the point at which planned demand and supply are equal." },
];

export function topicStats(events: LearningEvent[]) { const map = new Map<string, { attempts: number; correct: number; score: number }>(); for (const e of events) { if (!e.topic || e.type !== "question") continue; const current = map.get(e.topic) ?? { attempts: 0, correct: 0, score: 0 }; current.attempts += 1; if (e.correct) current.correct += 1; current.score = current.correct / current.attempts; map.set(e.topic, current); } return map; }
export function selectAdaptiveQuestions(events: LearningEvent[], count = 8, subject?: string) { const stats = topicStats(events); const candidates = QUESTION_BANK.filter(q => !subject || q.subject === subject); return [...candidates].sort((a, b) => { const sa = stats.get(a.topic); const sb = stats.get(b.topic); const weaknessA = sa ? 1 - sa.score : 0.65; const weaknessB = sb ? 1 - sb.score : 0.65; const difficultyA = a.difficulty === "hard" ? 0.2 : a.difficulty === "medium" ? 0.1 : 0; const difficultyB = b.difficulty === "hard" ? 0.2 : b.difficulty === "medium" ? 0.1 : 0; return (weaknessB + difficultyB) - (weaknessA + difficultyA); }).slice(0, count); }
export function recommendedResources(notes: NoteDoc[], papers: PYQPaper[], skills: SkillPost[], events: LearningEvent[], limit = 6): ResourceRecommendation[] { const stats = topicStats(events); const weakTopics = [...stats.entries()].sort((a, b) => a[1].score - b[1].score).map(([topic]) => topic); const keywords = weakTopics.slice(0, 5); const scoreText = (text: string) => keywords.reduce((score, k) => score + (text.toLowerCase().includes(k.toLowerCase()) ? 5 : 0), 0); const out: ResourceRecommendation[] = [...notes.map(n => ({ id: n.id, kind: "note" as const, title: n.title, subtitle: `${n.subject} · ${n.chapter}`, url: n.url, score: 3 + scoreText(`${n.subject} ${n.chapter} ${n.title}`), reason: keywords.length ? `Reinforces ${keywords[0]}` : "Good starting resource" })), ...papers.map(p => ({ id: p.id, kind: "pyq" as const, title: p.title, subtitle: `${p.subject} · ${p.klass} · ${p.year}`, url: p.url, score: 2 + scoreText(`${p.subject} ${p.title}`), reason: "Practice with exam-style questions" })), ...skills.map(s => ({ id: s.id, kind: "skill" as const, title: s.title, subtitle: `By ${s.authorName}`, url: s.classUrl || s.videoUrl || "#", score: 1 + scoreText(s.title), reason: "Learn from a peer" }))]; return out.sort((a, b) => b.score - a.score).slice(0, limit); }
export function peerMatches(profile: LearningProfile | null, profiles: LearningProfile[], limit = 5) { if (!profile) return []; const mine = new Set([...profile.subjects, ...profile.topics].map(x => x.toLowerCase())); return profiles.filter(p => p.userId !== profile.userId).map(p => { const their = [...p.subjects, ...p.topics].map(x => x.toLowerCase()); const overlap = their.filter(x => mine.has(x)).length; const goalBonus = p.goal && p.goal.toLowerCase() === profile.goal.toLowerCase() ? 2 : 0; return { profile: p, score: overlap * 3 + goalBonus, overlap }; }).filter(x => x.score > 0).sort((a, b) => b.score - a.score).slice(0, limit); }
export function analytics(events: LearningEvent[]) { const questions = events.filter(e => e.type === "question"); const correct = questions.filter(e => e.correct).length; const totalDuration = questions.reduce((s, e) => s + (e.durationSec || 0), 0); const days = new Set(events.map(e => e.createdAt.slice(0, 10))).size; const accuracy = questions.length ? correct / questions.length : 0; const stats = topicStats(events); const weakest = [...stats.entries()].sort((a, b) => a[1].score - b[1].score).slice(0, 3).map(([topic, s]) => ({ topic, accuracy: s.score })); return { questions: questions.length, correct, accuracy, totalDuration, activeDays: days, weakest }; }
