import { useMemo, useState } from "react";
import { BarChart3, Brain, CheckCircle2, Clock3, Users, Sparkles, Target, Trophy, RotateCcw } from "lucide-react";
import { notesStore, pyqStore, skillStore } from "@/stores";
import { authApi } from "@/lib/auth";
import { analytics, peerMatches, recommendedResources, selectAdaptiveQuestions } from "@/lib/learning-engine";
import { learningEventsStore, learningProfilesStore, recordLearningEvent, saveLearningProfile } from "@/lib/learning-store";

export function LearningIntelligencePanel() {
  const events = learningEventsStore.use();
  const profiles = learningProfilesStore.use();
  const notes = notesStore.use();
  const papers = pyqStore.use();
  const skills = skillStore.use();
  const stats = useMemo(() => analytics(events), [events]);
  const resources = useMemo(() => recommendedResources(notes, papers, skills, events), [notes, papers, skills, events]);
  const currentUid = authApi.current()?.uid;
  const me = profiles.find(p => p.userId === currentUid) ?? null;
  const matches = useMemo(() => peerMatches(me, profiles), [me, profiles]);

  return <section className="mt-12 space-y-6">
    <div><p className="text-xs font-mono uppercase tracking-widest text-rose-gold">new · learning intelligence</p><h2 className="font-serif text-3xl mt-1">Personalized learning, added to your progress.</h2><p className="text-sm text-muted-foreground mt-2 max-w-3xl">Your existing daily goals stay unchanged. This layer adds adaptive practice, analytics, resource recommendations and optional peer matching.</p></div>
    <div className="grid grid-cols-2 md:grid-cols-4 gap-3"><Metric icon={BarChart3} label="Accuracy" value={`${Math.round(stats.accuracy * 100)}%`} /><Metric icon={Brain} label="Questions" value={String(stats.questions)} /><Metric icon={Clock3} label="Study time" value={formatDuration(stats.totalDuration)} /><Metric icon={Target} label="Active days" value={String(stats.activeDays)} /></div>
    <div className="grid lg:grid-cols-2 gap-5"><AdaptiveQuiz events={events} /><ResourceRecommendations resources={resources.slice(0, 5)} /></div>
    <div className="grid lg:grid-cols-2 gap-5"><WeakTopics stats={stats} /><PeerLearning profiles={profiles} me={me} matches={matches} /></div>
  </section>;
}

function Metric({ icon: Icon, label, value }: { icon: typeof Brain; label: string; value: string }) { return <div className="glass-strong rounded-2xl p-4"><Icon className="w-4 h-4 text-rose-gold mb-3" /><div className="text-[10px] font-mono uppercase tracking-widest text-muted-foreground">{label}</div><div className="font-serif text-2xl mt-1">{value}</div></div>; }

function AdaptiveQuiz({ events }: { events: any[] }) {
  const [started, setStarted] = useState(false); const [answered, setAnswered] = useState<string[]>([]); const [selected, setSelected] = useState<number | null>(null); const [correct, setCorrect] = useState(0); const [total, setTotal] = useState(0); const [startedAt, setStartedAt] = useState(0); const [sessionEvents, setSessionEvents] = useState<any[]>([]);
  const current = useMemo(() => started ? selectAdaptiveQuestions([...events, ...sessionEvents], 20).find(q => !answered.includes(q.id)) ?? null : null, [events, sessionEvents, started, answered]);
  function start() { setStarted(true); setAnswered([]); setSelected(null); setCorrect(0); setTotal(0); setStartedAt(Date.now()); setSessionEvents([]); }
  function answer(index: number) { if (!current || selected !== null) return; const ok = index === current.answer; const event = { type: "question" as const, itemId: current.id, subject: current.subject, topic: current.topic, correct: ok, durationSec: Math.max(1, Math.round((Date.now() - startedAt) / 1000)) }; setSelected(index); setAnswered(a => [...a, current.id]); setTotal(n => n + 1); if (ok) setCorrect(n => n + 1); setSessionEvents(e => [...e, event]); recordLearningEvent(event); }
  if (!started) return <div className="glass-strong rounded-3xl p-6"><div className="flex items-center gap-3 mb-4"><Brain className="w-5 h-5 text-rose-gold" /><h3 className="font-serif text-2xl">Adaptive quiz</h3></div><p className="text-sm text-muted-foreground">Questions prioritize weak or unseen topics, then increase difficulty as your accuracy improves.</p><button onClick={start} className="btn-phoenix rounded-full px-5 py-2.5 text-sm mt-5">Start adaptive quiz</button></div>;
  if (!current) return <div className="glass-strong rounded-3xl p-6"><Trophy className="w-5 h-5 text-rose-gold mb-3" /><h3 className="font-serif text-2xl">Quiz complete</h3><p className="text-sm text-muted-foreground mt-2">{correct}/{total} correct. Your results now influence future selection.</p><button onClick={start} className="btn-ghost-gold rounded-full px-5 py-2.5 text-sm mt-5 inline-flex items-center gap-2"><RotateCcw className="w-4 h-4" /> Try again</button></div>;
  return <div className="glass-strong rounded-3xl p-6"><div className="flex justify-between text-[10px] font-mono uppercase tracking-widest text-muted-foreground"><span>{current.subject} · {current.topic}</span><span>{current.difficulty}</span></div><h3 className="font-serif text-xl leading-relaxed mt-4">{current.prompt}</h3><div className="grid gap-2 mt-5">{current.options.map((option, i) => <button key={option} disabled={selected !== null} onClick={() => answer(i)} className={`text-left rounded-xl p-3 border transition ${selected === null ? "glass hover:border-rose-gold/40" : i === current.answer ? "border-emerald-400/50 bg-emerald-400/10" : i === selected ? "border-crimson/50 bg-crimson/10" : "glass opacity-60"}`}><span className="font-mono text-xs mr-2">{String.fromCharCode(65 + i)}.</span>{option}</button>)}</div>{selected !== null && <div className="mt-4"><p className="text-sm font-medium">{selected === current.answer ? "Correct." : "Not quite."}</p><p className="text-xs text-muted-foreground mt-1">{current.explanation}</p><button onClick={() => setSelected(null)} className="btn-phoenix rounded-full px-4 py-2 text-xs mt-3">Next question</button></div>}</div>;
}

function ResourceRecommendations({ resources }: { resources: any[] }) { return <div className="glass rounded-3xl p-6"><div className="flex items-center gap-3 mb-4"><Sparkles className="w-5 h-5 text-rose-gold" /><h3 className="font-serif text-2xl">Recommended resources</h3></div>{resources.length === 0 ? <p className="text-sm text-muted-foreground">Complete some practice or add resources to unlock recommendations.</p> : <div className="space-y-2">{resources.map(r => <a key={`${r.kind}-${r.id}`} href={r.url} target="_blank" rel="noreferrer" className="block glass rounded-xl p-3 hover:border-rose-gold/30 transition"><div className="text-sm font-medium">{r.title}</div><div className="text-xs text-muted-foreground mt-1">{r.subtitle} · {r.reason}</div></a>)}</div>}</div>; }
function WeakTopics({ stats }: { stats: any }) { return <div className="glass rounded-3xl p-6"><div className="flex items-center gap-3 mb-5"><BarChart3 className="w-5 h-5 text-rose-gold" /><h3 className="font-serif text-2xl">Topics needing attention</h3></div>{stats.weakest.length === 0 ? <p className="text-sm text-muted-foreground">Your weakest topics appear here after practice.</p> : <div className="space-y-4">{stats.weakest.map((x: any) => <div key={x.topic}><div className="flex justify-between text-sm mb-1"><span>{x.topic}</span><span className="font-mono text-xs text-muted-foreground">{Math.round(x.accuracy * 100)}%</span></div><div className="h-2 rounded-full bg-foreground/10 overflow-hidden"><div className="h-full bg-rose-gold/70 rounded-full" style={{ width: `${Math.round(x.accuracy * 100)}%` }} /></div></div>)}</div>}</div>; }
function PeerLearning({ profiles, me, matches }: { profiles: any[]; me: any; matches: any[] }) { const [subjects, setSubjects] = useState(me?.subjects?.join(", ") ?? ""); const [topics, setTopics] = useState(me?.topics?.join(", ") ?? ""); const [goal, setGoal] = useState(me?.goal ?? ""); const [availability, setAvailability] = useState(me?.availability ?? ""); return <div className="glass-strong rounded-3xl p-6"><div className="flex items-center gap-3 mb-2"><Users className="w-5 h-5 text-rose-gold" /><h3 className="font-serif text-2xl">Peer learning</h3></div><p className="text-xs text-muted-foreground mb-5">Optional: share only the subjects, topics and study goals you choose.</p><div className="grid gap-2"><input value={subjects} onChange={e => setSubjects(e.target.value)} placeholder="Subjects: Mathematics, Physics" className="glass rounded-xl px-3 py-2 text-sm bg-transparent" /><input value={topics} onChange={e => setTopics(e.target.value)} placeholder="Topics: Vectors, Kinematics" className="glass rounded-xl px-3 py-2 text-sm bg-transparent" /><input value={goal} onChange={e => setGoal(e.target.value)} placeholder="Goal: JEE preparation" className="glass rounded-xl px-3 py-2 text-sm bg-transparent" /><input value={availability} onChange={e => setAvailability(e.target.value)} placeholder="Availability: evenings" className="glass rounded-xl px-3 py-2 text-sm bg-transparent" /><button onClick={() => saveLearningProfile({ subjects: split(subjects), topics: split(topics), goal: goal.trim(), availability: availability.trim() })} className="btn-phoenix rounded-xl py-2.5 text-sm mt-1">Save learning profile</button></div>{matches.length > 0 && <div className="mt-6 space-y-2"><div className="text-xs font-mono uppercase tracking-widest text-muted-foreground">Suggested peers</div>{matches.map((m: any) => <div key={m.profile.userId} className="glass rounded-xl p-3"><div className="text-sm">Shared subjects/topics: {m.overlap}</div><div className="text-xs text-muted-foreground mt-1">Goal: {m.profile.goal || "Not specified"}</div></div>)}</div>}{profiles.length === 0 && <p className="text-xs text-muted-foreground mt-4">No opted-in peers yet.</p>}</div>; }
function split(value: string) { return value.split(",").map(x => x.trim()).filter(Boolean).slice(0, 12); }
function formatDuration(seconds: number) { if (!seconds) return "0m"; const mins = Math.round(seconds / 60); return mins < 60 ? `${mins}m` : `${Math.floor(mins / 60)}h ${mins % 60}m`; }
